### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by Chimwemwe-127001** [Chimwemwe-127001/book-appointment-frontend#13]
# Kanban Setup
> ***We are a group of five***
1. Team 1 - [Chimwemwe-127001](https://github.com/Chimwemwe-127001)
2. Team 2 - [Ranjeet](https://github.com/thecodechaser )
3. Team 3 - [Ellis](https://github.com/mwanawabangona)
4. Team 4 - [Ritta](https://github.com/Buyaki01)
5. Team 5 - [Anselem](https://github.com/AnselemOdims )

### ***Link to kanban board: https://github.com/users/Chimwemwe-127001/projects/3*** :+1:
![Screenshot from 2022-05-10 11-22-22](https://user-images.githubusercontent.com/52143815/168111567-55c97ab0-4b06-4e55-b9db-11383588184f.png)
![Screenshot from 2022-05-10 11-22-46](https://user-images.githubusercontent.com/52143815/168111571-af38d222-2b6c-44db-9b9f-324abe52ef9c.png)
![Screenshot from 2022-05-10 11-22-58](https://user-images.githubusercontent.com/52143815/168111575-ac27eaa4-f174-46c7-b007-ef2434208472.png)
![Screenshot from 2022-05-10 11-23-02](https://user-images.githubusercontent.com/52143815/168111580-3e918a2e-1370-4b21-baf4-91b59054c392.png)

**Comment by MuriloRoque** [comment]
Hi @Chimwemwe-127001, @AnselemOdims, @Buyaki01, @mwanawabangona, @thecodechaser,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
